import CollectionCard from "../components/organism/CollectionCard";
import Head from "next/head";
import SlideShow from "../components/molecules/SlideShow";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SlideShow></SlideShow>
      <CollectionCard></CollectionCard>
    </>
  );
}
